### ISSUE TITLE
Can you be more specific about "newer version of bmp"？

### ISSUE THREAD

**Issue by czhang03** [ynkdir/vim-bgimg#1]

**Comment by ynkdir** [comment]
See https://en.wikipedia.org/wiki/BMP_file_format

There are several version of BMP file.

MS-Paint generates BMP file whoes DIB header is BITMAPINFOHEADER (size=40).  And LoadImage() function can load it.

Gimp generates BMP file whoes DIB header is BITMAPV4HEADER (size=108).  And LoadImage() function can not load it.

**Comment by czhang03** [comment]
I am sorry, but I used bmp generated by ms-paint, but this is not loading.
![capture1](https://cloud.githubusercontent.com/assets/10100995/13373441/6541b71a-dd36-11e5-8ad2-c5ab5a1a18e2.PNG)
![capture](https://cloud.githubusercontent.com/assets/10100995/13373442/66f4a5cc-dd36-11e5-89b0-abf074e9bf82.PNG)
is it because I am running windows 10?

**Comment by ynkdir** [comment]
bgimg#set_bg() is used to set background color which is replaced by image.

Try the following command.

``` vim
:call bgimg#set_bg(str2nr(synIDattr(hlID('Normal'), 'bg#')[1:], 16))
:call bgimg#set_image('C:/Users/zcsxo/OneDrive/surface-Document/personalize/vimbackground.bmp')
```

`str2nr(synIDattr(hlID('Normal'), 'bg#')[1:], 16)` may not work in vimrc or when synIDattr() returns empty.  You can specify background color manually like `:call bgimg#set_bg(0xFFFFFF)` then.

**Comment by czhang03** [comment]
even `call bgimg#set_bg(0xFFFFFF)` is not working...
the background color is not changing to white... 
does it has anything to do with I am using a 64bit gvim?

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 23 2016 
13:07:27)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1403
Compiled by veegee@veegee-win8
```

**Comment by czhang03** [comment]
I have tried a x86 version, it is still not working

**Comment by czhang03** [comment]
I tried couple of build of vim, and begin to wander if I have correctly installed the plugin.

I have tried putting the `autoload` folder inside of the `.vim/autoload`
and I have tried putting the directory in vundle's `bundle` directory...

Am I doing anything wrong here with the install?

**Comment by ynkdir** [comment]
0xFFFFFF (white) is an example.  If background color is black, it should be `:call bgimg#set_bg(0)`.  You can check your background color with `:hi Normal` or `:echo synIDattr(hlID('Normal'), 'bg#')`.

**Comment by czhang03** [comment]
![capture](https://cloud.githubusercontent.com/assets/10100995/13375936/1b2329f8-dd7b-11e5-856f-594f5892f8b5.PNG)

I think it is not changing ...

**Comment by ynkdir** [comment]
> #1b1d1e

Then, `:call bgimg#set_bg(0x1B1D1E)`.

**Comment by czhang03** [comment]
That is working for now, thanks...
Is there a way to just display a single image on the corner?

**Comment by ynkdir** [comment]
It might be possible to implement.  But I have no time.

**Comment by czhang03** [comment]
thanks for your time.
